title: Victoria Porto ðŸ‡¬ðŸ‡§
description: Aerospace & Mechanical Engineering | Stanford University
logo: /images/profilepic.jpg
theme: jekyll-theme-minimal

resume: /images/Porto_CV.pdf

github:
  is_project_page: false
